spring.application.name=SpringAi

spring.ai.openai.api-key=${}
spring.ai.openai.chat.options.model=gpt-4o
spring.ai.vectorstore.pgvector.index-type=hnsw
spring.ai.vectorstore.pgvector.distance-type=cosine_distance
spring.ai.vectorstore.pgvector.dimensions=1536

spring.docker.compose.lifecycle-management=start_only

#                    always
spring.sql.init.mode=never
#spring.ai.vectorstore.pgvector.initialize-schema=true
#spring.ai.vectorstore.pgvector.schema-actions=create